---
abstract: 'Delimited Text Processing'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Delimited
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Text::Delimited:
    file: lib/Text/Delimited.pm
    version: 2.10
requires:
  Symbol: 0
  Test::More: 0
  Test::Simple: 0
  perl: 5.006001
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Text-Delimited
  repository: git://github.com/bennie/perl-Text-Delimited.git
version: 2.10
